### ISSUE TITLE
vagrant image doesn't have jdk

### ISSUE THREAD

**Issue by klucar** [mesos/myriad#57]
setup-yarn-2.sh fails in the vagrant vm because there is no jdk installed by default.

**Comment by bgulla** [comment]
it seems that it is because the apt-get repos are updated until setup-yarn-1 is run. We should move the apt-get install -y oracle-java8-installer  from the Vagrantfile to setup-yarn-1.sh.

**Comment by bgulla** [comment]
It seems like editing out the 'apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF' line in the Vagrant file allowed the Vagrant image to fully build and thus install JAVA 8. @klucar I believe that the issue might be due to a firewall on the network, but I will try to recreate tonight on a different network.

**Comment by klucar** [comment]
I just re-provisioned over my home network and it went fine. I didn't have to edit the Vagrantfile either.
